### ISSUE TITLE
Write Brain / Heart  / Blood texts

### ISSUE THREAD

**Issue by Felixmil** [esqLABS/0buzz#41]
+ remove header

**Comment by StephanSchaller** [comment]
Texts:

**Blood Measurements**

Blood concentrations of caffeine are crucial for understanding its overall exposure in the body. Measuring caffeine levels in the blood provides direct insight into how much caffeine is absorbed and available for distribution to various organs. These measurements serve as the foundation for Physiologically Based Pharmacokinetic (PBPK) modeling, which simulates caffeine's journey through the body over time. By using blood data, we can predict organ-specific concentrations, helping to tailor dosing strategies. Blood measurements are essential for correlating caffeine intake with its physiological effects and ensuring safe and effective consumption levels.
Effective, safe levels range from 1 to 10 mg/L while levels above 40 mg/L can be fatal.

**Heart Exposure and Cardiac Safety**

Caffeine impacts the heart both directly and indirectly. Directly, it influences cardiac muscle cells by modulating calcium ion channels, leading to increased heart rate and contractility. Indirectly, caffeine stimulates the central nervous system, causing the release of adrenaline, which further elevates heart activity (see: Brain). Understanding caffeine concentrations in the heart is vital for assessing cardiac safety, especially in sensitive individuals. PBPK modeling uses blood levels to predict heart exposure, allowing us to evaluate potential risks like palpitations or arrhythmias. This helps in optimizing caffeine dosing to enjoy its benefits while minimizing cardiac side effects.

**Brain Exposure and Caffeine's Effects**

Caffeine's primary effects occur in the brain, where it blocks adenosine receptors to promote alertness and reduce fatigue. The concentration of caffeine reaching the brain determines the intensity of these cognitive effects. Direct measurement is challenging, so PBPK models use blood levels to estimate brain exposure. This modeling helps us understand how different doses affect mental performance and mood. By simulating brain concentrations, we can personalize caffeine intake to achieve desired effects like improved concentration while avoiding side effects such as anxiety or insomnia. Accurate brain exposure predictions are key to maximizing caffeine's cognitive benefits safely.
