### ISSUE TITLE
Smoker popup text

### ISSUE THREAD

**Issue by AKostiv8** [esqLABS/0buzz#66]
![image](https://github.com/user-attachments/assets/e4802ed7-eaae-49a6-b604-a909730e02a8)

**Comment by StephanSchaller** [comment]
Use this text (@wilbertdew, feel free to refine):

**Smoking and Caffeine Metabolism**

Smoking can significantly increase the metabolism of caffeine. Tobacco smoke induces the liver enzyme CYP1A2, which is primarily responsible for breaking down caffeine. As a result, smokers process caffeine more rapidly, leading to lower blood caffeine levels and diminished stimulatory effects. This means that smokers may require higher doses of caffeine to achieve the same alertness as non-smokers. Conversely, if a person quits smoking, their caffeine metabolism slows down, potentially increasing caffeine levels and the risk of side effects unless caffeine intake is adjusted accordingly.
