### ISSUE TITLE
Show Efficiency levels popup text

### ISSUE THREAD

**Issue by AKostiv8** [esqLABS/0buzz#84]
![Screenshot 2024-11-27 163532](https://github.com/user-attachments/assets/ca8b81dc-ffc6-4db9-ad9e-e6d8f39f01a7)

**Comment by StephanSchaller** [comment]
**Therapeutic Thresholds for Effective and Safe Caffeine Dosing**

**Lower Threshold (1 mg/L)**

Caffeine plasma concentrations need to exceed 1 mg/L to produce noticeable stimulatory effects like increased alertness and enhanced cognitive performance. Using Physiologically Based Pharmacokinetic (PBPK) modeling, we can predict how different doses raise plasma levels above this minimum effective concentration. This helps in determining the optimal dosing required to achieve desired benefits without unnecessary intake.

**Upper Threshold (10 mg/L)**

Plasma concentrations above 10 mg/L increase the risk of adverse effects such as jitteriness, anxiety, insomnia, and elevated heart rate. PBPK modeling aids in forecasting when caffeine levels might approach this upper limit, allowing for adjustments in dosing to prevent exceeding safe exposure. By staying below this threshold, we balance efficacy with safety, ensuring optimal caffeine use.
